name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run tests
      run: go test -v ./...

    - name: Build
      run: go build -v ./...

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - Bug fixes and improvements
        draft: false
        prerelease: false

  go-proxy:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Trigger Go Proxy
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        curl -X GET "https://proxy.golang.org/github.com/reinanbr/chronus/@v/${VERSION}.info"
